[package]
name = "directip-arrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow2 = "0.16.0"
directip = { version = "0.2.5", path = "../" }
