[package]
name = "directip-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directip = {path="../"}
object_store = "0.5.5"
